### ISSUE TITLE
excella-trans-1.5がexcella-core-2.0に依存しているため使用できない。

### ISSUE THREAD

**Issue by mrdShinse** [excella-core/excella-trans#2]
excella-transを使用しようとして、pom.xmlに以下の記載をしました。
```xml
    <dependencies>
        <dependency>
            <groupId>org.bbreak.excella</groupId>
            <artifactId>excella-trans</artifactId>
            <version>1.5</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>excella.bbreak.org</id>
            <name>bBreak Systems Excella</name>
            <url>http://excella-core.github.io/maven2/</url>
        </repository>
    </repositories>
```

しかし、mavenでビルドをすると以下のエラーがでました。
Failed to execute goal on project learning-poi: Could not resolve dependencies for project com.wakanashi:learning-poi:jar:1.0-SNAPSHOT: Failure to find org.bbreak.excella:excella-core:jar:2.0 in http://repo.jenkins-ci.org/public/ was cached in the local repository, resolution will not be reattempted until the update interval of repo.jenkins-ci.org has elapsed or updates are forced -> [Help 1]

Tag v1.5のpomにexcella-core-2.0への依存性が記載されていますが、
私の環境からはダウンロードできないようです。
https://github.com/excella-core/excella-trans/blob/v1.5/pom.xml

これは、私の書き方に問題があるのでしょうか？それともtrans-1.5のtagに問題があるのでしょうか？

**Comment by kamisono-bb** [comment]
trans-1.5のタグに問題があります。
masterの方は修正していますので、それに合わせて、pom.xmlのexcella-coreのバージョンを1.9に変更してください。

**Comment by kamisono-bb** [comment]
v1.6にて修正しました。
